graph LR
A-->B-->C
node-1["Label with (parens) and [brackets]"] --o node-2
A-- text with spaces -->C
A --x D
X <--> Y
subgraph Plain Title
Q
end
E ~~~ F
  A -. dotted .-> F
G[Line one<br/>line two] == thick ==> H
this is garbage ###
